field.widget.settings.date_recur_modular_sierra:
  type: mapping
  label: 'Sierra widget settings'
  mapping:
    interpreter:
      type: string
      label: 'Interpreter instance ID'
    date_format_type:
      type: string
      label: 'Date format type to display occurrences and excluded occurrences.'
    occurrences_modal:
      type: boolean
      label: 'Whether to enable occurrences modal.'
